- LS_COLORS
Differentiate between SETUID and SETGID to reflect their relative significance to security. Addresses #21
> New, louder colors for files with SETUID and SETGID property.

- LS_COLORS
* `.RData` R database file
* `.r` and `.R` script files
* `.gs` GrADS script file
* `.nc` NetCDF database
* `.Rproj` RStudio project file
> colours for various files (R, GrADS, NetCDF)

- LS_COLORS
Added vector graphics extensions. Moved .svg to vector. Added .zoo archive; additional partition and font extensions.
> More graphics filetypes

- LS_COLORS
> Add .rpm file extension to packaged apps

- LS_COLORS
https://github.com/kovidgoyal/kitty
> Explicitly support kitty terminal

- LS_COLORS
(aria2c - versatile download utility)
> Add .aria2 for aria2c "control file"

- LS_COLORS
Surprised we didn't have this one already
> Add README.md for document file formats

- README.markdown
Thanks to @maximbaz for maintaining this package and bringing it to my attention in #62
> Add installation instructions for Archlinux AUR

- LS_COLORS
I added Clojure and Scala file extensions to the list.
> Added Clojure and Scala

- README.markdown
Follow up to #110 –  Zsh installation method via Zplugin. I've added the requested private section for description of Zplugin installation method.
> Updated README – information on loading via Zplugin (Zsh)

- LS_COLORS
Some file types i use regularly that i noticed weren't in
> Add some file types

- LS_COLORS
> Add more key-value file

- LS_COLORS
Zstandard archives and tab separated values
> .zst and .tsv

- LS_COLORS
https://docs.racket-lang.org/drracket/drracket-files.html
> Add Racket extension

- README.markdown
> Name the local files `.LS_COLORS` not `.dircolors`

- LS_COLORS
- run_tests
- tests/no_dupes
Adds a test for overloaded extensions. Also removes overloaded extensions I found with the test.
> Test dupes

- README.markdown
> Fix installation instructions in README

- LS_COLORS
This adds two additional extensions for the Sublime text editor.
> Added sublime settings and workspace extensions.

- LS_COLORS
* .xsd (W3C Schema)
* .dtd (OASIS Document Type Definition)
* .sgml (ISO Standard Generalized Markup Language)
* .rng (OASIS RELAX NG)
* .rnc (OASIS RELAX NG Compact)
> Added additional markup language extensions:

- LS_COLORS
- README.markdown
> Add docs on dependencies

- README.markdown
> Add dependencies to TOC

- LS_COLORS
Add scala script from https://ammonite.io/#ScalaScripts (https://github.com/lihaoyi/ammonite)
> Add scala script .sc

- LS_COLORS
RStudio theme config file added to LS_COLORS.
> Added .rstheme to LS_COLORS

- LS_COLORS
Added the following ZSH environment config files:
.zshenv
.zprofile
.zlogin
.zlogout
.zshrc is already included in '*rc'.
> Added ZSH environment config

- .github/workflows/build.yml
Should fix https://github.com/trapd00r/LS_COLORS/pull/183#issuecomment-1019529504
> Fix GitHub action logic

- .editorconfig
- .github/workflows/tests.yaml
- .pre-commit-config.yaml
- tests/works_without_env
Addresses https://github.com/trapd00r/LS_COLORS/pull/207#issuecomment-1819608522
> test: Add regression test for non-existent env var

- LS_COLORS
added extensions `.prisma` for Prisma Schema files
> added .prisma extension

- LS_COLORS
Adding some books format
azw/azw3 are used by kindle
fb2 -- i get for some shop in my country
> Add some book formats
