trapd00r/LS_COLORS

README.markdown

@trapd00r, I've corrected a typographical error in the documentation of the [LS_COLORS](https://github.com/trapd00r/LS_COLORS) project. You should be able to merge this pull request automatically. However, if this was intentional or if you enjoy living in linguistic squalor, please let me know and [create an issue](https://github.com/thoppe/orthographic-pedant/issues/new) on my home repository.

Fixed typographical error, changed arbitary to arbitrary in README.

---

buildsuite

Per #39, `grep -P` has unpredictable behavior depending on the local implementation. Therefore, this pull request eliminates the dependency on grep via an additional `sed` expression.

Eliminated dependency on 'grep -P'

---

LS_COLORS

Haskell Source files now appear with the same attributes as plain
Haskell Source files.

Added the 'lhs' filetype for Literate Haskell Source files.  Literate

---

LS_COLORS

This will use the foreground color and makes LS_COLORS usable with a
light background.
Ref: https://github.com/trapd00r/LS_COLORS/issues/28.

Use "NONE" for FILE and NORMAL

---

LS_COLORS

Core file name is defined in /proc/sys/kernel/core_pattern

Add color for Linux core dump file

---

LS_COLORS

Hi,
I've added a python color for [project jupyter](https://jupyter.org/)'s notebooks which are quite popular in data science/academia.
Cheers,
Max

jupyter lab/notebook ipynb extension added next to py

---

README.markdown

README: big clean-up and adding fish shell instructions

---

LS_COLORS

Added colors for `.nix` files (used by NixOS/nix) and `.dhall` files. `.nix` files are used to build derivations in the nix system and hence are colored in the same way as `Makefile`. `.dhall` files are used as a substitute for `.yaml` files and take on the same coloring.

Nix and dhall

---

README.markdown
install.sh

The quotes in the install script and corresponding `README` section didn't match and weren't paired.

Fix install script quotes

---

LS_COLORS

NDJSON appears to be the a fork of JSON Lines.

NDJSON support

---

LS_COLORS

`.jsonnet` is defined [here](https://jsonnet.org/learning/getting_started.html)
`.libsonnet` is defined [here](https://jsonnet.org/learning/tutorial.html)

Add jsonnet

---

LS_COLORS

Adds support for Asciidoc / Asciidoctor file extensions
Asciidoc is a markup format similar to Markdown, with more features.
- adds *.adoc and *.asciidoc according to https://asciidoctor.org/docs/asciidoc-recommended-practices/#document-extension
- *.asc wasn't added as it created a duplication with another format
- used the same colour scheme as other document formats, namely markdown

Add support for Asciidoc format

---

LS_COLORS

CRX and XPI files are packaged Chrome/Firefox browser extensions with
a ZIP archived source tree.
References:
.crx: https://developer.chrome.com/docs/extensions/mv3/linux_hosting/
.xpi: https://wiki.mozilla.org/Add-ons/Extension_Signing

Add crx for Chrome and xpi for Firefox extensions

---

LS_COLORS

* Emacs has the `el` extension for Emacs lisp.  Byte-compiled lisp has
`elc`.  Natively compiled lisp has `eln`.  Org-mode has the `org`
extension.

Add Emacs file extensions

---

LS_COLORS

This change restructures the LS_COLORS file without making any changes to dircolors output, as I confirmed via the Makefile.
- vim-specific folds and annotations are removed.
- Sorting of the extensions is reworked a bit, although this still isn't as scientific as I would like. It's progress though.
- Comments are moved inline and many new comments are added. These comments are formatted to prepare for parsing the LS_COLORS file out into style sheets to help enforce stylistic consistency.

LS_COLORS restructuring

---

LS_COLORS

adds br file type from my #202 request

ADD br file type

---

.editorconfig

This adds an entry for the `Makefile` in the EditorConfig file. Without this, my editor automatically uses spaces for indentation.

style(editorconfig): Add rule for Makefile

---

Makefile

This improves the reproducability of the Makefile by setting `LC_ALL`. For examples, `sort` will give more consistent output, regardless of the user environment's default language.
Closes #194

fix: Reset `LC_ALL` in Makefile

---

Makefile

As mentioned in the linked issue, the previous syntax caused a syntax error if `XDG_DATA_HOME` was undefined.
```console
$ unset XDG_DATA_HOME
$ make install
/bin/sh: ${$HOME/.local/share}: bad substitution
make: *** [install] Error 1
```
This does away with the `$$` escaping, and leans into Make's standard `$()` substitution syntax. The logic goes like this:
- If `XDG_DATA_HOME` is not defined, assign it to `$HOME/.local/share` (now, value of `$HOME` is evaluated right away instead of being deferred; effectively changes nothing)
- Quote `$(XDG_DATA_HOME)`, in case parts of it contain whitespace (Make does not evaluate the quotation marks, Bash will once `$(XDG_DATA_HOME)` is substituted)
This also removes the `export` - it's not necessary
Closes #201

fix: Makefile syntax and whitespace quoting

---

.pre-commit-config.yaml
LS_COLORS

- Add Containerfile and .containerignore
- pre-commit autoupdate
See https://opencontainers.org/

Add Containerfile

---

LS_COLORS

Added support for:
- `.ml`, `.mli`, `.mll`, `.mly` for OCaml module, interface, lexer, and parser files
- `.opam`, `dune`, `dune-project` for OCaml Opam packaging and Dune build files
- `.sexp` for S-expression files (widely used with OCaml)
- `Cargo.toml` and `Cargo.lock` for Rust Cargo build and lock files
- `.gradle` for Java Gradle files
- Numerous files used by the Bazel build tool

Added support for multiple file types
